"""
Demo seed data for the OSINT Protest Map.

Used as fallback when external APIs (GDELT, HAPI, ACLED) are unreachable,
and as a dedicated /api/protest-map?demo=true endpoint for previews.
"""

from datetime import datetime, timezone, timedelta
import random

_NOW = datetime.now(timezone.utc)


def _ago(hours: int) -> str:
    return (_NOW - timedelta(hours=hours)).isoformat()


DEMO_PROTESTS = [
    {
        "id": "demo001",
        "title": "Thousands march in Paris against pension reform cuts",
        "url": "https://www.bbc.com/news/world-europe",
        "source": "bbc.com",
        "sourcecountry": "France",
        "publishedAt": _ago(1),
        "image": "https://ichef.bbci.co.uk/news/1024/branded_news/assets/img/2024/01/protest.jpg",
        "lat": 48.8566,
        "lon": 2.3522,
        "country": "France",
        "threatLevel": "HIGH",
        "eventType": "Protest",
        "dataSource": "GDELT",
        "language": "English",
        "notes": "Police deployed water cannons as demonstrators blocked major intersections.",
    },
    {
        "id": "demo002",
        "title": "Anti-government protests erupt in Dhaka over election results",
        "url": "https://www.reuters.com/world/asia-pacific",
        "source": "reuters.com",
        "sourcecountry": "Bangladesh",
        "publishedAt": _ago(2),
        "image": None,
        "lat": 23.8103,
        "lon": 90.4125,
        "country": "Bangladesh",
        "threatLevel": "CRITICAL",
        "eventType": "Riot",
        "dataSource": "GDELT",
        "language": "English",
        "notes": "Clashes between protesters and security forces reported. 3 fatalities confirmed.",
    },
    {
        "id": "demo003",
        "title": "Workers' strike shuts down ports across Argentina",
        "url": "https://apnews.com/world-news",
        "source": "apnews.com",
        "sourcecountry": "Argentina",
        "publishedAt": _ago(3),
        "image": None,
        "lat": -34.6037,
        "lon": -58.3816,
        "country": "Argentina",
        "threatLevel": "MEDIUM",
        "eventType": "Strike",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo004",
        "title": "Pro-democracy rally draws 50,000 in Seoul",
        "url": "https://www.aljazeera.com/news",
        "source": "aljazeera.com",
        "sourcecountry": "South Korea",
        "publishedAt": _ago(4),
        "image": None,
        "lat": 37.5665,
        "lon": 126.9780,
        "country": "South Korea",
        "threatLevel": "LOW",
        "eventType": "Rally",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo005",
        "title": "Violent clashes as farmers block highways in India",
        "url": "https://timesofindia.indiatimes.com",
        "source": "timesofindia.com",
        "sourcecountry": "India",
        "publishedAt": _ago(2),
        "image": None,
        "lat": 28.6139,
        "lon": 77.2090,
        "country": "India",
        "threatLevel": "HIGH",
        "eventType": "Protest",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo006",
        "title": "Climate protesters glue themselves to London roads",
        "url": "https://www.theguardian.com/environment",
        "source": "theguardian.com",
        "sourcecountry": "United Kingdom",
        "publishedAt": _ago(5),
        "image": None,
        "lat": 51.5074,
        "lon": -0.1278,
        "country": "United Kingdom",
        "threatLevel": "LOW",
        "eventType": "Demonstration",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo007",
        "title": "Mass protests against president continue in Nairobi",
        "url": "https://www.reuters.com/world/africa",
        "source": "reuters.com",
        "sourcecountry": "Kenya",
        "publishedAt": _ago(6),
        "image": None,
        "lat": -1.2921,
        "lon": 36.8219,
        "country": "Kenya",
        "threatLevel": "HIGH",
        "eventType": "Protest",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo008",
        "title": "Gaza solidarity march in Washington DC draws thousands",
        "url": "https://apnews.com",
        "source": "apnews.com",
        "sourcecountry": "United States",
        "publishedAt": _ago(7),
        "image": None,
        "lat": 38.8951,
        "lon": -77.0364,
        "country": "United States",
        "threatLevel": "MEDIUM",
        "eventType": "March",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo009",
        "title": "Protesters storm parliament building in Tbilisi",
        "url": "https://www.euronews.com",
        "source": "euronews.com",
        "sourcecountry": "Georgia",
        "publishedAt": _ago(8),
        "image": None,
        "lat": 41.6938,
        "lon": 44.8015,
        "country": "Georgia",
        "threatLevel": "CRITICAL",
        "eventType": "Riot",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo010",
        "title": "Anti-austerity protests in Athens turn violent",
        "url": "https://www.ekathimerini.com",
        "source": "ekathimerini.com",
        "sourcecountry": "Greece",
        "publishedAt": _ago(9),
        "image": None,
        "lat": 37.9838,
        "lon": 23.7275,
        "country": "Greece",
        "threatLevel": "HIGH",
        "eventType": "Protest",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo011",
        "title": "Protests in Tehran over water shortage crisis",
        "url": "https://www.bbc.com/persian",
        "source": "bbc.com",
        "sourcecountry": "Iran",
        "publishedAt": _ago(10),
        "image": None,
        "lat": 35.6892,
        "lon": 51.3890,
        "country": "Iran",
        "threatLevel": "HIGH",
        "eventType": "Protest",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo012",
        "title": "Teachers strike in Mexico City demanding pay rise",
        "url": "https://www.reuters.com",
        "source": "reuters.com",
        "sourcecountry": "Mexico",
        "publishedAt": _ago(11),
        "image": None,
        "lat": 19.4326,
        "lon": -99.1332,
        "country": "Mexico",
        "threatLevel": "MEDIUM",
        "eventType": "Strike",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo013",
        "title": "University students protest in Cairo against crackdown",
        "url": "https://www.aljazeera.com",
        "source": "aljazeera.com",
        "sourcecountry": "Egypt",
        "publishedAt": _ago(12),
        "image": None,
        "lat": 30.0444,
        "lon": 31.2357,
        "country": "Egypt",
        "threatLevel": "MEDIUM",
        "eventType": "Protest",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo014",
        "title": "Truckers' strike paralyses São Paulo highways",
        "url": "https://www.folha.uol.com.br",
        "source": "folha.uol.com.br",
        "sourcecountry": "Brazil",
        "publishedAt": _ago(3),
        "image": None,
        "lat": -23.5505,
        "lon": -46.6333,
        "country": "Brazil",
        "threatLevel": "MEDIUM",
        "eventType": "Strike",
        "dataSource": "GDELT",
        "language": "Portuguese",
    },
    {
        "id": "demo015",
        "title": "Anti-coup protesters fired on in Myanmar",
        "url": "https://www.reuters.com/world/asia",
        "source": "reuters.com",
        "sourcecountry": "Myanmar",
        "publishedAt": _ago(1),
        "image": None,
        "lat": 16.8661,
        "lon": 96.1951,
        "country": "Myanmar",
        "threatLevel": "CRITICAL",
        "eventType": "Violent Protest",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo016",
        "title": "Fuel price protests spread across Nigeria",
        "url": "https://www.vanguardngr.com",
        "source": "vanguardngr.com",
        "sourcecountry": "Nigeria",
        "publishedAt": _ago(4),
        "image": None,
        "lat": 9.0820,
        "lon": 8.6753,
        "country": "Nigeria",
        "threatLevel": "HIGH",
        "eventType": "Protest",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo017",
        "title": "Hundreds rally in Kyiv for faster EU integration",
        "url": "https://www.kyivpost.com",
        "source": "kyivpost.com",
        "sourcecountry": "Ukraine",
        "publishedAt": _ago(5),
        "image": None,
        "lat": 50.4501,
        "lon": 30.5234,
        "country": "Ukraine",
        "threatLevel": "LOW",
        "eventType": "Rally",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo018",
        "title": "Hong Kong pro-democracy vigil draws silent crowd",
        "url": "https://www.scmp.com",
        "source": "scmp.com",
        "sourcecountry": "Hong Kong",
        "publishedAt": _ago(6),
        "image": None,
        "lat": 22.3193,
        "lon": 114.1694,
        "country": "Hong Kong",
        "threatLevel": "LOW",
        "eventType": "Vigil",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo019",
        "title": "Demonstrations in Islamabad over economic crisis",
        "url": "https://www.dawn.com",
        "source": "dawn.com",
        "sourcecountry": "Pakistan",
        "publishedAt": _ago(7),
        "image": None,
        "lat": 33.7294,
        "lon": 73.0931,
        "country": "Pakistan",
        "threatLevel": "HIGH",
        "eventType": "Demonstration",
        "dataSource": "GDELT",
        "language": "English",
    },
    {
        "id": "demo020",
        "title": "Yellow Vest-style protests return in Lyon",
        "url": "https://www.lemonde.fr",
        "source": "lemonde.fr",
        "sourcecountry": "France",
        "publishedAt": _ago(14),
        "image": None,
        "lat": 45.7640,
        "lon": 4.8357,
        "country": "France",
        "threatLevel": "MEDIUM",
        "eventType": "Protest",
        "dataSource": "GDELT",
        "language": "French",
    },
]

DEMO_HAPI_EVENTS = [
    {
        "id": "hapi-eth-001",
        "country": "Ethiopia",
        "countryCode": "ETH",
        "admin1": "Oromia",
        "eventType": "Protests",
        "eventCount": 28,
        "fatalities": 4,
        "date": (_NOW - timedelta(days=2)).strftime("%Y-%m-%d"),
        "lat": 9.1450,
        "lon": 40.4897,
        "threatLevel": "CRITICAL",
        "dataSource": "HAPI/OCHA",
    },
    {
        "id": "hapi-sdn-001",
        "country": "Sudan",
        "countryCode": "SDN",
        "admin1": "Khartoum",
        "eventType": "Protests",
        "eventCount": 15,
        "fatalities": 2,
        "date": (_NOW - timedelta(days=1)).strftime("%Y-%m-%d"),
        "lat": 15.5007,
        "lon": 32.5599,
        "threatLevel": "CRITICAL",
        "dataSource": "HAPI/OCHA",
    },
    {
        "id": "hapi-mli-001",
        "country": "Mali",
        "countryCode": "MLI",
        "admin1": "Bamako",
        "eventType": "Demonstrations",
        "eventCount": 9,
        "fatalities": 0,
        "date": (_NOW - timedelta(days=3)).strftime("%Y-%m-%d"),
        "lat": 12.6392,
        "lon": -8.0029,
        "threatLevel": "MEDIUM",
        "dataSource": "HAPI/OCHA",
    },
    {
        "id": "hapi-hti-001",
        "country": "Haiti",
        "countryCode": "HTI",
        "admin1": "Ouest",
        "eventType": "Protests",
        "eventCount": 22,
        "fatalities": 6,
        "date": (_NOW - timedelta(days=1)).strftime("%Y-%m-%d"),
        "lat": 18.5944,
        "lon": -72.3074,
        "threatLevel": "CRITICAL",
        "dataSource": "HAPI/OCHA",
    },
    {
        "id": "hapi-ven-001",
        "country": "Venezuela",
        "countryCode": "VEN",
        "admin1": "Caracas",
        "eventType": "Protests",
        "eventCount": 18,
        "fatalities": 1,
        "date": (_NOW - timedelta(days=2)).strftime("%Y-%m-%d"),
        "lat": 10.4806,
        "lon": -66.9036,
        "threatLevel": "HIGH",
        "dataSource": "HAPI/OCHA",
    },
    {
        "id": "hapi-nga-001",
        "country": "Nigeria",
        "countryCode": "NGA",
        "admin1": "Lagos",
        "eventType": "Protests",
        "eventCount": 12,
        "fatalities": 0,
        "date": (_NOW - timedelta(days=4)).strftime("%Y-%m-%d"),
        "lat": 6.5244,
        "lon": 3.3792,
        "threatLevel": "MEDIUM",
        "dataSource": "HAPI/OCHA",
    },
    {
        "id": "hapi-irq-001",
        "country": "Iraq",
        "countryCode": "IRQ",
        "admin1": "Baghdad",
        "eventType": "Protests",
        "eventCount": 8,
        "fatalities": 0,
        "date": (_NOW - timedelta(days=3)).strftime("%Y-%m-%d"),
        "lat": 33.3152,
        "lon": 44.3661,
        "threatLevel": "MEDIUM",
        "dataSource": "HAPI/OCHA",
    },
    {
        "id": "hapi-som-001",
        "country": "Somalia",
        "countryCode": "SOM",
        "admin1": "Mogadishu",
        "eventType": "Protests",
        "eventCount": 5,
        "fatalities": 3,
        "date": (_NOW - timedelta(days=1)).strftime("%Y-%m-%d"),
        "lat": 2.0469,
        "lon": 45.3182,
        "threatLevel": "CRITICAL",
        "dataSource": "HAPI/OCHA",
    },
]

DEMO_STREAMS = [
    {"id": "yt-s1", "title": "LIVE: Global Protest Coverage — BBC World", "embedUrl": "https://www.youtube.com/embed?listType=search&list=protest+live+now&autoplay=0", "type": "youtube_search", "country": "Global", "thumbnail": None},
    {"id": "yt-s2", "title": "LIVE: Civil Unrest — Al Jazeera", "embedUrl": "https://www.youtube.com/embed?listType=search&list=demonstration+live+news&autoplay=0", "type": "youtube_search", "country": "Global", "thumbnail": None},
    {"id": "yt-s3", "title": "Strike Action Live News", "embedUrl": "https://www.youtube.com/embed?listType=search&list=strike+news+live&autoplay=0", "type": "youtube_search", "country": "Global", "thumbnail": None},
    {"id": "yt-s4", "title": "Riot & Unrest Live Stream", "embedUrl": "https://www.youtube.com/embed?listType=search&list=riot+live+stream&autoplay=0", "type": "youtube_search", "country": "Global", "thumbnail": None},
    {"id": "yt-s5", "title": "March & Rally Coverage", "embedUrl": "https://www.youtube.com/embed?listType=search&list=march+protest+rally&autoplay=0", "type": "youtube_search", "country": "Global", "thumbnail": None},
    {"id": "yt-s6", "title": "Civil Resistance Live", "embedUrl": "https://www.youtube.com/embed?listType=search&list=civil+unrest+live&autoplay=0", "type": "youtube_search", "country": "Global", "thumbnail": None},
    {"id": "yt-s7", "title": "Protest News — France 24", "embedUrl": "https://www.youtube.com/embed?listType=search&list=france+protest+live&autoplay=0", "type": "youtube_search", "country": "France", "thumbnail": None},
    {"id": "yt-s8", "title": "Asia Protest Coverage", "embedUrl": "https://www.youtube.com/embed?listType=search&list=asia+protest+demonstration&autoplay=0", "type": "youtube_search", "country": "Asia", "thumbnail": None},
]

DEMO_IMAGES = [
    {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Paris_protests_2019.jpg/640px-Paris_protests_2019.jpg", "title": "Paris protest march", "source": "Wikimedia", "publishedAt": _ago(2)},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/2019-2020_Hong_Kong_protests_-_Admiralty_-_20190901_-_10.jpg/640px-2019-2020_Hong_Kong_protests_-_Admiralty_-_20190901_-_10.jpg", "title": "Hong Kong protest crowd", "source": "Wikimedia", "publishedAt": _ago(8)},
]


def get_demo_protests() -> dict:
    summary = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0}
    for e in DEMO_PROTESTS:
        lvl = e.get("threatLevel", "LOW")
        if lvl in summary:
            summary[lvl] += 1
    return {
        "events": DEMO_PROTESTS,
        "totalCount": len(DEMO_PROTESTS),
        "sources": ["GDELT (demo)"],
        "lastUpdated": _NOW.isoformat(),
        "threatSummary": summary,
    }


def get_demo_hapi() -> dict:
    return {
        "conflictEvents": DEMO_HAPI_EVENTS,
        "totalCount": len(DEMO_HAPI_EVENTS),
        "lastUpdated": _NOW.isoformat(),
    }


def get_demo_streams() -> dict:
    return {
        "liveStreams": DEMO_STREAMS,
        "images": DEMO_IMAGES,
        "lastUpdated": _NOW.isoformat(),
    }
